---
- name: Install Java Repo
  command: add-apt-repository ppa:openjdk-r/ppa
  tags: java

- name: Install Java
  apt:
    update_cache: yes
    name: openjdk-11-jdk
    install_recommends: no
  tags: java