---
- name: Creates directory
  file:
    recurse: yes
    path: /usr/share/man/man1
    state: directory

- name: Install Oracle Java 11
  apt:
    update_cache: yes
    name: openjdk-11-jdk
    state: latest
    install_recommends: no
  with_items:
    - ca-certificates
  tags: java  